@startuml
left to right direction

예매 "*" -- "1"상영
상영 "*" -- "1"영화

package 할인정책패키지  {
영화 "1" -- "0..1" 할인정책
금액할인정책 --> 할인정책
비율할인정책 --> 할인정책
}

package 할인조건패키지 {
할인정책 "1" --- "1..*" 할인조건
순번조건 --> 할인조건
기간조건 --> 할인조건
}
@enduml