@startuml

class "Movie" as m
class "DiscountPolicy" as p
interface "DiscountCondition" as c

class SequenceCondition implements c
class PeriodCondition implements c

class "AmountDiscountPolicy" as ad
class "PercentDiscountPolicy" as pd
class "NoneDiscountPolicy" as nd

m -> p :discountPolicy

ad -up-> p
pd -up-> p
nd -up-> p

p -right-> c : * \n conditions
@enduml
