@startuml
left to right direction

object ":Theater" as t
object "audience : Audience" as a
object "ticketSeller:TicketSeller" as s
object "ticketOffice:TicketOffice" as o

t --> s : 1: sellTo(audience)
s --> o : 2: ticket = getTicket()\n 4: plausAmount(amount)
s -> a : 3: amount = buy(ticket)
@enduml