@startuml
left to right direction

object ":Theater" as t
object "audience : Audience" as a
object "bag:Bag" as b
object "ticketSeller:TicketSeller" as s
object "ticketOffice:TicketOffice" as o

t --> a : 1: bag = getBag()
t --> b : 2: invited = hasInvitation()
t --> s : 3: office = getTicketOffice()
t --> o : 4: ticket = getTicket()

@enduml